import { createApi } from '@reduxjs/toolkit/query/react'
import { baseQueryWithReauth } from '../../../core/api/base-query-with-reauth'
import { FollowUserInDTO } from './dto/follow-user.in'
import { GetProfileDTO } from './dto/profile.in'

interface ProfileParams {
	username: string
}

export const profileApi = createApi({
	reducerPath: 'profileApi',
	baseQuery: baseQueryWithReauth,
	endpoints: builder => ({
		getProfile: builder.query<GetProfileDTO, ProfileParams>({
			query: ({ username }) => ({
				url: `/profiles/${username}`,
				method: 'get',
			}),
		}),

		followUser: builder.mutation<FollowUserInDTO, ProfileParams>({
			query: ({ username }) => ({
				url: `/profiles/${username}/follow`,
				method: 'post',
			}),
		}),

		unfollowUser: builder.mutation<FollowUserInDTO, ProfileParams>({
			query: ({ username }) => ({
				url: `/profiles/${username}/follow`,
				method: 'delete',
			}),
		}),
	}),
})

export const {
	useGetProfileQuery,
	useFollowUserMutation,
	useUnfollowUserMutation,
} = profileApi // autogenerated hook
