import { createApi } from '@reduxjs/toolkit/query/react'
import { blogtubBaseQuery } from '../../../core/blogtub-base-query'
import { GetProfileDTO } from './dto/profile.in'

interface ProfileParams {
	username: string
}

export const profileApi = createApi({
	reducerPath: 'profileApi',
	baseQuery: blogtubBaseQuery,
	endpoints: builder => ({
		getProfile: builder.query<GetProfileDTO, ProfileParams>({
			query: ({ username }) => ({
				url: `/profiles/${username}`,
				method: 'get',
			}),
		}),
	}),
})

export const { useGetProfileQuery } = profileApi // autogenerated hook
